name: documentation
on:
  push:
    branches:
      - unstable
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Install Swift dependencies
        run: |
          sudo apt-get install clang libicu-dev
          wget https://download.swift.org/swift-5.6.1-release/ubuntu2004/swift-5.6.1-RELEASE/swift-5.6.1-RELEASE-ubuntu20.04.tar.gz
          tar xzf swift-5.6.1-RELEASE-ubuntu20.04.tar.gz
          echo "$(pwd)/swift-5.6.1-RELEASE-ubuntu20.04/usr/bin" >> $GITHUB_PATH

      - name: Clean up documentation branch
        run: |
          git branch -D documentation || true
          git checkout -b documentation

      - name: Run docc
        run: |
          cd "${GITHUB_WORKSPACE}" && ./scripts/docc.sh

      - name: Add and commit documentation
        run: |
          git config --global user.email "docbot@github.com"
          git config --global user.name "docbot"
          cd "${GITHUB_WORKSPACE}" && git add "docs/*" && git commit -m "Update docs."

      - name: Push the new branch
        run: |
          cd "${GITHUB_WORKSPACE}" && git push --force origin documentation:documentation

