name: macos-bazel
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-darwin-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-darwin-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Run tests
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test --test_output=errors //src/tests:Tests
